name: Go CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v6

      # 2. Setup Go
      - name: Set up Go
        uses: actions/setup-go@v6.1.0
        with:
          go-version: 1.25.3

      # 3. Enable Go modules
      - name: Enable Go modules
        run: go env -w GO111MODULE=on

      # 4. Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 5. Generate code
      - name: Run go generate
        run: go generate ./...

      # 6. Run tests
      - name: Run tests
        run: go test ./... -v

      # 7. Build binary
      - name: Build binary
        run: go build -o advent ./...

      # 8. Run the program
      - name: Run program
        run: ./advent
